apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fleet
resources:
- namespace.yaml
- kafka.yaml
- job-create-topics.yaml
- discovery-server.yaml
- fleet.yaml
- bridge.yaml
- dashboard.yaml
- prometheus.yaml
- grafana.yaml
